"""initial schema

Revision ID: 3d8a27f7f865
Revises: 
Create Date: 2026-07-04 17:43:03.225048

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3d8a27f7f865'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_audit_log_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_target_type'), ['target_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('companies',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('registration_number', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('logo_key', sa.String(length=512), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('default_language', sa.String(length=2), nullable=False),
    sa.Column('default_pdf_template', sa.String(length=64), nullable=False),
    sa.Column('invoice_reference_prefix', sa.String(length=8), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_companies_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_companies'))
    )
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_companies_organization_id'), ['organization_id'], unique=False)

    op.create_table('org_memberships',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_org_memberships_organization_id_organizations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_org_memberships_user_id_users')),
    sa.PrimaryKeyConstraint('organization_id', 'user_id', name=op.f('pk_org_memberships'))
    )
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_subscriptions_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('organization_id', name=op.f('uq_subscriptions_organization_id'))
    )
    op.create_table('clients',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('vat_number', sa.String(length=32), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('postal_code', sa.String(length=16), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('is_business', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_clients_company_id_companies')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_clients_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_organization_id'), ['organization_id'], unique=False)

    op.create_table('products',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('billing_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('pipeline_stage', sa.String(length=100), nullable=True),
    sa.Column('default_vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_products_company_id_companies')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_products_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_organization_id'), ['organization_id'], unique=False)

    op.create_table('sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_sequences_company_id_companies')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_sequences_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sequences')),
    sa.UniqueConstraint('organization_id', 'company_id', 'scope', name=op.f('uq_sequences_organization_id'))
    )
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sequences_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sequences_organization_id'), ['organization_id'], unique=False)

    op.create_table('invoices',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('sequence_global', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_discount_type', sa.String(length=20), nullable=True),
    sa.Column('invoice_discount_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('invoice_discount_reason', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('pdf_template', sa.String(length=64), nullable=False),
    sa.Column('subtotal_ht', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_discount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_ttc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.Column('voided_by_credit_note_id', sa.Uuid(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_invoices_client_id_clients')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_invoices_company_id_companies')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invoices_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('organization_id', 'company_id', 'reference', name=op.f('uq_invoices_organization_id')),
    sa.UniqueConstraint('organization_id', 'company_id', 'sequence_global', name=op.f('uq_invoices_organization_id'))
    )
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoices_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoices_organization_id'), ['organization_id'], unique=False)

    op.create_table('credit_notes',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('sequence_global', sa.Integer(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('pdf_template', sa.String(length=64), nullable=False),
    sa.Column('subtotal_ht', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_vat', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('total_ttc', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_credit_notes_client_id_clients')),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_credit_notes_company_id_companies')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_credit_notes_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_credit_notes_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_notes')),
    sa.UniqueConstraint('organization_id', 'company_id', 'reference', name=op.f('uq_credit_notes_organization_id')),
    sa.UniqueConstraint('organization_id', 'company_id', 'sequence_global', name=op.f('uq_credit_notes_organization_id'))
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_notes_organization_id'), ['organization_id'], unique=False)

    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('vat_category', sa.String(length=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_legal_mention', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=20), nullable=True),
    sa.Column('discount_value', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('discount_reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invoice_lines_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_lines_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_lines_organization_id'), ['organization_id'], unique=False)

    op.create_table('payments',
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('paid_on', sa.Date(), nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payments_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_payments_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_organization_id'), ['organization_id'], unique=False)

    op.create_table('credit_note_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('credit_note_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('vat_category', sa.String(length=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('vat_legal_mention', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], name=op.f('fk_credit_note_lines_credit_note_id_credit_notes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_credit_note_lines_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_note_lines'))
    )
    with op.batch_alter_table('credit_note_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_lines_credit_note_id'), ['credit_note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_note_lines_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_note_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_lines_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_note_lines_credit_note_id'))

    op.drop_table('credit_note_lines')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_organization_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    with op.batch_alter_table('invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_lines_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_lines_invoice_id'))

    op.drop_table('invoice_lines')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_organization_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_company_id'))
        batch_op.drop_index(batch_op.f('ix_credit_notes_client_id'))

    op.drop_table('credit_notes')
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoices_organization_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_company_id'))
        batch_op.drop_index(batch_op.f('ix_invoices_client_id'))

    op.drop_table('invoices')
    with op.batch_alter_table('sequences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sequences_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sequences_company_id'))

    op.drop_table('sequences')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_organization_id'))
        batch_op.drop_index(batch_op.f('ix_products_company_id'))

    op.drop_table('products')
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_organization_id'))
        batch_op.drop_index(batch_op.f('ix_clients_company_id'))

    op.drop_table('clients')
    op.drop_table('subscriptions')
    op.drop_table('org_memberships')
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_companies_organization_id'))

    op.drop_table('companies')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_log_target_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_organization_id'))

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###
