"""templates are per document type

Revision ID: 57b2467bf9f2
Revises: 70355c684846
Create Date: 2026-08-28 20:26:39.228221

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '57b2467bf9f2'
down_revision: str | Sequence[str] | None = '70355c684846'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#  Autogenerate again proposed re-renaming the unique constraints on
#  credit_notes and invoices. That is drift between the dev database and
#  revision 165748c8c55f, not this change, and it is removed by hand for the
#  same reason as last time: a migration should do what its message says.
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_document_templates_name'), type_='unique')
        batch_op.create_unique_constraint('uq_document_templates_name', ['organization_id', 'company_id', 'doc_type', 'name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_constraint('uq_document_templates_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_document_templates_name'), ['organization_id', 'company_id', 'name'])

    # ### end Alembic commands ###
