"""expenses and document templates

Revision ID: 70355c684846
Revises: 165748c8c55f
Create Date: 2026-08-28 18:23:46.886592

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70355c684846'
down_revision: str | Sequence[str] | None = '165748c8c55f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#  Autogenerate also proposed re-renaming the unique constraints on
#  credit_notes and invoices. That drift is between the dev database and
#  revision 165748c8c55f, not this change, and it was removed by hand: a
#  migration should do what its message says and nothing else.
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_templates',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('doc_type', sa.String(length=20), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('draft_blocks', sa.JSON(), nullable=False),
    sa.Column('draft_appearance', sa.JSON(), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_document_templates_company_id_companies')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_document_templates_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_templates')),
    sa.UniqueConstraint('organization_id', 'company_id', 'name', name='uq_document_templates_name')
    )
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_templates_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_document_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('expenses',
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=True),
    sa.Column('source_document_key', sa.String(length=512), nullable=True),
    sa.Column('supplier_vat_number', sa.String(length=32), nullable=True),
    sa.Column('supplier_invoice_number', sa.String(length=64), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('detected_tva', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('recoverable_tva', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=False),
    sa.Column('classification', sa.JSON(), nullable=True),
    sa.Column('duplicate_of_id', sa.Uuid(), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('fk_expenses_company_id_companies')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['expenses.id'], name=op.f('fk_expenses_duplicate_of_id_expenses')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_expenses_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_duplicate_of_id'), ['duplicate_of_id'], unique=False)
        batch_op.create_index('ix_expenses_invoice_date', ['organization_id', 'invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_expenses_state', ['organization_id', 'state'], unique=False)
        batch_op.create_index('ix_expenses_supplier_document', ['organization_id', 'company_id', 'supplier_vat_number', 'supplier_invoice_number'], unique=False)

    op.create_table('template_versions',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('blocks', sa.JSON(), nullable=False),
    sa.Column('appearance', sa.JSON(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_template_versions_organization_id_organizations')),
    sa.ForeignKeyConstraint(['template_id'], ['document_templates.id'], name=op.f('fk_template_versions_template_id_document_templates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_versions')),
    sa.UniqueConstraint('organization_id', 'template_id', 'version', name='uq_template_versions_version')
    )
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_template_versions_template_id'), ['template_id'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_snapshot', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('template_snapshot')

    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_versions_template_id'))
        batch_op.drop_index(batch_op.f('ix_template_versions_organization_id'))

    op.drop_table('template_versions')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_supplier_document')
        batch_op.drop_index('ix_expenses_state')
        batch_op.drop_index(batch_op.f('ix_expenses_organization_id'))
        batch_op.drop_index('ix_expenses_invoice_date')
        batch_op.drop_index(batch_op.f('ix_expenses_duplicate_of_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_company_id'))

    op.drop_table('expenses')
    with op.batch_alter_table('document_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_templates_organization_id'))
        batch_op.drop_index(batch_op.f('ix_document_templates_company_id'))

    op.drop_table('document_templates')
    # ### end Alembic commands ###
