"""interface language on the user

Revision ID: a40b35409ffe
Revises: 57b2467bf9f2
Create Date: 2026-08-28 23:26:25.583509

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a40b35409ffe'
down_revision: str | Sequence[str] | None = '57b2467bf9f2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


#  The recurring credit_notes/invoices constraint drift is removed by hand
#  again — it belongs to revision 165748c8c55f, not to this change.
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=2), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
